"""
Generate diverse example notebooks for all domains
Run with: python tests/generate_all_notebooks.py
"""

import os
import sys
import traceback

from tests.helpers.notebook_html import (
    create_ab_testing_notebook,
    create_climate_notebook,
    create_finance_notebook,
    create_genomics_notebook,
)

# API URL must be provided via environment variable
API_URL = os.getenv("ARTIFACTA_API_URL")
if not API_URL:
    print("ERROR: ARTIFACTA_API_URL environment variable must be set")
    print("Example: export ARTIFACTA_API_URL=http://localhost:8000")
    sys.exit(1)


def generate_ab_testing_notebooks():
    """Generate A/B testing notebooks"""
    print("Generating A/B Testing notebooks...")

    variant_a = {"conversion_rate": 0.0523, "avg_order_value": 125.50, "bounce_rate": 0.4210}

    variant_b = {"conversion_rate": 0.0587, "avg_order_value": 132.75, "bounce_rate": 0.3895}

    create_ab_testing_notebook(
        project_id="ab-testing",
        run_ids=["run_001", "run_002"],
        variant_a_metrics=variant_a,
        variant_b_metrics=variant_b,
        api_url=API_URL,
    )
    print("A/B Testing notebooks created")


def generate_finance_notebooks():
    """Generate finance notebooks"""
    print("Generating Finance notebooks...")

    portfolio_metrics = {
        "sharpe_ratio": 1.85,
        "sortino_ratio": 2.12,
        "max_drawdown": -0.1523,
        "annual_return": 0.1845,
        "volatility": 0.1234,
    }

    create_finance_notebook(
        project_id="finance",
        run_ids=["run_001"],
        portfolio_metrics=portfolio_metrics,
        api_url=API_URL,
    )
    print("Finance notebooks created")


def generate_genomics_notebooks():
    """Generate genomics notebooks"""
    print("Generating Genomics notebooks...")

    sequence_stats = {
        "sequence_length": 15420,
        "gc_content": 45.2,
        "n_count": 12,
        "coding_regions": 8,
        "alignment_score": 8745,
    }

    create_genomics_notebook(
        project_id="genomics", run_ids=["run_001"], sequence_stats=sequence_stats, api_url=API_URL
    )
    print("Genomics notebooks created")


def generate_climate_notebooks():
    """Generate climate notebooks"""
    print("Generating Climate notebooks...")

    climate_metrics = {
        "global_temp_change": 2.1,
        "co2_concentration": 420.5,
        "sea_level_rise": 0.85,
        "arctic_ice_loss": 13.2,
    }

    create_climate_notebook(
        project_id="climate", run_ids=["run_001"], climate_metrics=climate_metrics, api_url=API_URL
    )
    print("Climate notebooks created")


def generate_computer_vision_notebooks():
    """Generate computer vision notebooks (already exists, just call it)"""
    print("Computer Vision notebooks already generated by test_computer_vision.py")


if __name__ == "__main__":
    print("\nGenerating diverse example notebooks for all domains...\n")

    try:
        generate_ab_testing_notebooks()
        generate_finance_notebooks()
        generate_genomics_notebooks()
        generate_climate_notebooks()
        generate_computer_vision_notebooks()

        print("\nAll notebooks generated successfully!")
        print("View them in the Artifacta UI\n")

    except Exception as e:
        print(f"\nError generating notebooks: {e}")
        import traceback

        traceback.print_exc()
        sys.exit(1)
